import Head from 'next/head'
import Footer from '../components/Footer'
import NavbarComponent from '../components/Navbar'
import Link from 'next/link'

export default function Home () {
  return (
    <main className="d-flex flex-column min-vh-100">
      <Head>
        <title>Team 1 Challenge 10</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarComponent />
      <div className="container-fluid">
        <div className="px-4 py-5 my-5 text-center flex-grow-1">
          <h1 className="display-5 fw-bold">Traditional Game</h1>
          <div className="col-lg-6 mx-auto">
            <h2 className="lead mb-4">Please Login For Play The Game</h2>
            <div className="py-5 d-grid gap-2 d-sm-flex justify-content-sm-center">
              <Link href="/login">
                <button type="button" className="btn btn-outline-warning btn-lg px-4">
                  Login
                </button>
              </Link>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </main>
  )
}
